export const FILES = [
  "category",
  "chat",
  "education",
  "follow",
  "forum",
  "forumcomment",
  "forumlike",
  "insight",
  "institute",
  "institutedisc",
  "institutediscreaction",
  "institutereview",
  "message",
  "notification",
  "profile",
  "refcode",
  "user",
  "wallet",
] as const;
